<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Ancelotow.DbCore.Performance</RootNamespace>
        <PackageId>Ancelotow.DbCore.Performance</PackageId>
        <Version>0.0.1</Version>
        <Authors>Ancelotow</Authors>
        <Description>
            - Add specification design pattern including INNER JOIN creation            
        </Description>
        <RepositoryUrl>https://github.com/Ancelotow/dotnet-db-core-performance</RepositoryUrl>
    </PropertyGroup>

</Project>
